### ISSUE TITLE
AioQuickClient如何监听连接状态？

### ISSUE THREAD

**Issue by 129duckflew** [smartboot/smart-socket#10]
在SpringBoot启动的时候注册若干个client，但是client发起连接之后没有找到注册监听连接状态的监听器，netty中有bootstrap.connect().addListener()的方法，请问smartSocket如何实现？

**Comment by smthing** [comment]
抱歉哈~对springboot和netty不熟，不太理解你说的监听器是个什么东西。

**Comment by 129duckflew** [comment]
> 
简而言之，我需要获取AioQuickClient发起连接之后是否连接成功,目前看到的是连接失败会直接抛出异常，我需要的是能够自动发起重连，或者提供连接失败的回调入口

**Comment by smthing** [comment]
无异常并能返回Session就说明连接成功了。

自动重连的功能需要使用者自行实现。因为网络断开只是个结果，smart-socket无法知道导致该结果的原因为何，也就无法做出合适的处理策略。有些场景下断开就结束了，而有些场景又需要重连，作为通信框架很难兼顾。 

 如果你需要感知网络断开，关注一下 SESSION_CLOSED这个状态机便可。
