### ISSUE TITLE
有没有选项打印收发的socket数据

### ISSUE THREAD

**Issue by wangran99** [smartboot/smart-socket#13]
就像netty的那种格式：
![image](https://github.com/smartboot/smart-socket/assets/17898332/31ce26b5-d07d-4cdf-a985-2c3c8033a544)

**Comment by smthing** [comment]
有一款码流检测插件：https://smartboot.tech/smart-socket/plugin-stream-monitor.html

**Comment by wangran99** [comment]
![image](https://github.com/smartboot/smart-socket/assets/17898332/80a44f13-476a-4659-bb48-fa84b86ab83a)
引入依赖后，没有对应的增加插件的方法：
![image](https://github.com/smartboot/smart-socket/assets/17898332/eda69495-21a8-4a43-92f3-c9c37cd7012f)

**Comment by wangran99** [comment]
改用 aio-pro解决问题：
![image](https://github.com/smartboot/smart-socket/assets/17898332/a8ab391d-d589-46fe-8b7d-48bb8adb0bee)
之前用的是文档里提到的aio-core。
