### ISSUE TITLE
怎么安装?

### ISSUE THREAD

**Issue by liaogang** [smartboot/smart-socket#2]
android新手提问，怎么在android studio里面安装?

**Comment by liaogang** [comment]
兼容android5和6吗?

**Comment by smthing** [comment]
smart-socket是基于jdk7开发的AIO通信框架，Android的低版本无法使用，不过我们有专为Android朋友开发的NIO版:https://gitee.com/smartboot/smart-ioc
你可以通过maven或gradle引入到你的工程中，仓库地址：https://mvnrepository.com/artifact/org.smartboot.ioc/smart-ioc/1.0.0
