### ISSUE TITLE
串口通信能用这个库实现吗？

### ISSUE THREAD

**Issue by CrazyBoyFeng** [smartboot/smart-socket#5]
我看代码和 example 都是 tcp、udp 这种 ip 层以上的协议。  

我需要跟硬件通信：串口在系统层面是个文件描述符 `FileDescriptor`，通过往这个特殊的文件读写数据来跟硬件通信。  
数据是“指令+分隔符+内容”这种格式。我的业务处理是：接到硬件传来的数据后，通过互联网与用户交互。收到用户的反馈请求后再往硬件写入。

**Comment by CrazyBoyFeng** [comment]
应该是我想多了，系统层面上，`File` 的 IO 都是阻塞的。

**Comment by smthing** [comment]
smart-socket 的定位是解决通信问题，文件 IO 不在规划范围内。
